# Generated by Django 6.0.6 on 2026-07-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                (
                    "system_uptime",
                    models.FloatField(help_text="Uptime percentage (e.g., 99.9)"),
                ),
                (
                    "tickets_resolved",
                    models.IntegerField(
                        help_text="Total support tickets resolved this month"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Optimal", "Optimal"),
                            ("Action Required", "Action Required"),
                        ],
                        max_length=50,
                    ),
                ),
                ("last_updated", models.DateField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(db_index=True, max_length=100)),
                ("device_type", models.CharField(default="Unknown", max_length=50)),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ONLINE",
                        max_length=15,
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("last_ping", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alert_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
