import smtplib
from email.message import EmailMessage
import datetime
import time

# --- CONFIGURATION ---
SENDER_EMAIL = "tomaszwilczynski02@gmail.com"  
RECEIVER_EMAIL = "tomaszwilczynski02@gmail.com" 
APP_PASSWORD = "rrsh emky mywy pict"     

print("\n[SYSTEM] Initializing background task schedule...")
time.sleep(1)

# --- BUILD THE EMAIL ---
msg = EmailMessage()
msg['Subject'] = f"Automated MATRIX Report - {datetime.date.today()}"
msg['From'] = SENDER_EMAIL
msg['To'] = RECEIVER_EMAIL

msg.set_content("""
Hi Team,

This is an automated daily report generated by the MATRIX Operations Portal.

-----------------------------------
DAILY SUMMARY:
- System Status: ONLINE
- External API: Connected
- Active Threats: 3 Unresolved
- Hardware Alerts: 1 Device Offline (Gate Controller)
-----------------------------------

This background reporting task executed successfully.

Best,
MATRIX Automated System
""")

# --- SEND THE EMAIL ---
print("[SYSTEM] Compiling dashboard data...")
time.sleep(1)
print("[SYSTEM] Connecting to secure mail server...")

try:
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(SENDER_EMAIL, APP_PASSWORD)
        smtp.send_message(msg)
        print(f"[SUCCESS] Automated report successfully sent to {RECEIVER_EMAIL}!\n")
except Exception as e:
    print(f"\n[ERROR] Failed to send email: {e}\n")